let Game = require('./src/Game')

let game = new Game()
console.log('status', game.status)
game.start()
console.log('status', game.status)
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
console.log('status', game.status)
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
console.log('status', game.status)
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
console.log('status', game.status)
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
console.log('status', game.status)
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
console.log('status', game.status)
game.makeGuess([0, 1, 2, 3])
console.log(game.tentatives())
console.log('status', game.status)
